"""Generates every voiced line in ECHO with Microsoft neural voices (edge-tts) and bakes them into vo.js.

Sources: radio(...) calls in echo.html, subtitle lines in prologue.js, and the BARKS table in echo.html.
Re-run after changing any dialogue; unchanged lines are reused from ./cache.
    python assets/voice/generate_voices.py
"""
import asyncio, base64, hashlib, io, json, os, re, subprocess, sys

import edge_tts

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
CACHE = os.path.join(HERE, 'cache')

# speaker -> (voice, rate, pitch)
VOICES = {
    'ECHO': ('en-US-ChristopherNeural', '-12%', '-10Hz'),
    'MARCUS': ('en-US-GuyNeural', '-4%', '-4Hz'),
    'CONDUCTOR': ('en-GB-ThomasNeural', '-18%', '-14Hz'),
    'LENA': ('en-US-AvaNeural', '-10%', '+0Hz'),
    'E1': ('en-US-SteffanNeural', '+8%', '-6Hz'),
    'E2': ('en-US-RogerNeural', '+6%', '-10Hz'),
    'E3': ('en-GB-RyanNeural', '+8%', '-8Hz'),
}


def js_unescape(s):
    return re.sub(r'\\(.)', lambda m: {'n': '\n', 't': '\t'}.get(m.group(1), m.group(1)), s)


def collect():
    game = io.open(os.path.join(ROOT, 'echo.html'), encoding='utf-8').read()
    pro = io.open(os.path.join(ROOT, 'prologue.js'), encoding='utf-8').read()
    lines = []  # (speaker, text), prologue first so it decodes first
    for who, text in re.findall(r"\{ at: [\d.]+,(?: who: '([A-Z]+)',)? text: '((?:[^'\\]|\\.)*)' \}", pro):
        lines.append((who or 'ECHO', js_unescape(text)))
    for who, q in re.findall(r"radio\('([A-Z]+)',\s*(\"(?:[^\"\\]|\\.)*\"|'(?:[^'\\]|\\.)*')\)", game):
        lines.append((who, js_unescape(q[1:-1])))
    barks = json.loads(game.split('/*json*/', 1)[1].split('/*end*/', 1)[0])
    for texts in barks.values():
        for t in texts:
            for v in ('E1', 'E2', 'E3'):
                lines.append((v, t))
    seen, out = set(), []
    for l in lines:
        if l not in seen:
            seen.add(l); out.append(l)
    return out


def duration(path):
    r = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', path], capture_output=True, text=True)
    return round(float(r.stdout.strip()), 3)


async def render(who, text, path):
    voice, rate, pitch = VOICES[who]
    # TTS reads typographic quotes/ellipses oddly; speak a cleaned copy
    spoken = text.replace('“', '').replace('”', '').replace('…', '').replace('—', ',').strip()
    for attempt in range(4):
        try:
            await edge_tts.Communicate(spoken, voice, rate=rate, pitch=pitch).save(path)
            return
        except Exception as e:
            if attempt == 3: raise
            await asyncio.sleep(1.5 * (attempt + 1))


async def main():
    os.makedirs(CACHE, exist_ok=True)
    lines = collect()
    todo = []
    for who, text in lines:
        f = os.path.join(CACHE, hashlib.sha1(f'{VOICES[who]}|{who}|{text}'.encode()).hexdigest()[:12] + '.mp3')
        if not os.path.exists(f) or os.path.getsize(f) < 500:
            todo.append((who, text, f))
    print(f'{len(lines)} lines, {len(todo)} to render')
    sem = asyncio.Semaphore(6)
    async def one(item):
        async with sem:
            await render(*item)
            print('  ok', item[0], item[1][:60])
    await asyncio.gather(*(one(t) for t in todo))
    out = {}
    for who, text in lines:
        f = os.path.join(CACHE, hashlib.sha1(f'{VOICES[who]}|{who}|{text}'.encode()).hexdigest()[:12] + '.mp3')
        ft = f[:-4] + '_t.mp3'
        if not os.path.exists(ft):  # trim the dead air TTS leaves at both ends
            trim = 'silenceremove=start_periods=1:start_threshold=-48dB,areverse,silenceremove=start_periods=1:start_threshold=-48dB,areverse,apad=pad_dur=0.08'
            subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', f, '-af', trim, '-ac', '1', '-b:a', '56k', ft], check=True)
        out[f'{who}|{text}'] = {'d': duration(ft), 'b': base64.b64encode(open(ft, 'rb').read()).decode()}
    js = '// generated by generate_voices.py — neural voice lines, base64 mp3\nwindow.VO_LINES = ' + json.dumps(out, ensure_ascii=False) + ';\n'
    io.open(os.path.join(HERE, 'vo.js'), 'w', encoding='utf-8').write(js)
    print(f'vo.js: {len(js) / 1e6:.2f} MB')
    json.dump({k: v['d'] for k, v in out.items()}, io.open(os.path.join(HERE, 'durations.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)


if __name__ == '__main__':
    asyncio.run(main())
